export interface ReportField {
  label: string
  value: string
}

// A tool-agnostic report shape so any calculator can produce a branded PDF.
export interface EstimateReport {
  toolTitle: string
  headlineLabel: string
  headlineLow: number
  headlineHigh: number
  /** Secondary figures shown under the headline (e.g. method, breakdown). */
  breakdown: ReportField[]
  /** The inputs the user entered. */
  fields: ReportField[]
  stateNote?: string
}

const SITE = 'tryballpark.com'

// Kept deliberately strong so the estimate can never be treated as a promise.
const DISCLAIMER =
  'This report is a free, automated educational estimate generated by Ballpark ' +
  '(tryballpark.com). It is not legal advice, not a valuation of any claim, and not a ' +
  'guarantee or promise of any settlement, recovery, or outcome. No attorney-client ' +
  'relationship is created by this report. Actual settlements depend on the evidence, ' +
  'insurance policy limits, jurisdiction, the specific facts of your case, and ' +
  'negotiation, and may be significantly higher or lower than the range shown. Do not ' +
  'rely on this report as the basis for any legal or financial decision. Consult a ' +
  'licensed attorney in your state for advice about your situation.'

const usd = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
})

// Generates and downloads a one-page PDF. jsPDF is imported dynamically so it
// only loads when the user actually clicks download.
export async function downloadEstimatePdf(report: EstimateReport): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })

  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const M = 56
  const contentW = pageW - M * 2
  const ink: [number, number, number] = [17, 24, 39]
  const soft: [number, number, number] = [75, 85, 99]
  const faint: [number, number, number] = [156, 163, 175]
  let y = M

  // Brand header
  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(...ink)
  doc.text('Ballpark', M, y)
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(...faint)
  doc.text(SITE, pageW - M, y, { align: 'right' })
  y += 16
  doc.setDrawColor(229, 231, 235).line(M, y, pageW - M, y)
  y += 28

  // Tool title + generated date
  doc.setFont('helvetica', 'bold').setFontSize(14).setTextColor(...ink)
  doc.text(report.toolTitle, M, y)
  y += 16
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(...faint)
  doc.text(`Estimate generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, M, y)
  y += 30

  // Headline range
  doc.setFontSize(9).setTextColor(...faint)
  doc.text(report.headlineLabel.toUpperCase(), M, y)
  y += 24
  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(...ink)
  doc.text(`${usd.format(report.headlineLow)} to ${usd.format(report.headlineHigh)}`, M, y)
  y += 22
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(...soft)
  for (const b of report.breakdown) {
    doc.text(`${b.label}: ${b.value}`, M, y)
    y += 16
  }
  y += 14

  // Inputs
  doc.setDrawColor(229, 231, 235).line(M, y - 14, pageW - M, y - 14)
  doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(...ink)
  doc.text('Your inputs', M, y)
  y += 20
  doc.setFont('helvetica', 'normal').setFontSize(10)
  for (const f of report.fields) {
    doc.setTextColor(...faint).text(f.label, M, y)
    doc.setTextColor(...ink).text(f.value, M + 230, y)
    y += 16
  }
  y += 12

  if (report.stateNote) {
    doc.setFontSize(10).setTextColor(...soft)
    doc.text(doc.splitTextToSize(report.stateNote, contentW), M, y)
  }

  // Disclaimer pinned to the bottom
  doc.setDrawColor(229, 231, 235).line(M, pageH - 150, pageW - M, pageH - 150)
  doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(...soft)
  doc.text('Important', M, pageH - 132)
  doc.setFont('helvetica', 'normal').setTextColor(...faint)
  doc.text(doc.splitTextToSize(DISCLAIMER, contentW), M, pageH - 118)

  doc.save('ballpark-estimate.pdf')
}
