import type { SettlementResult } from './settlement'
import { formatUSD } from './format'

export interface ReportField {
  label: string
  value: string
}

export interface EstimateReport {
  toolTitle: string
  result: SettlementResult
  fields: ReportField[]
  stateNote?: string
}

const SITE = 'tryballpark.com'

// Kept deliberately strong so the estimate can never be treated as a promise.
const DISCLAIMER =
  'This report is a free, automated educational estimate generated by Ballpark ' +
  '(tryballpark.com). It is not legal advice, not a valuation of any claim, and not a ' +
  'guarantee or promise of any settlement, recovery, or outcome. No attorney-client ' +
  'relationship is created by this report. Actual settlements depend on the evidence, ' +
  'insurance policy limits, jurisdiction, the specific facts of your case, and ' +
  'negotiation, and may be significantly higher or lower than the range shown. Do not ' +
  'rely on this report as the basis for any legal or financial decision. Consult a ' +
  'licensed attorney in your state for advice about your situation.'

// Generates and downloads a one-page PDF of the inputs + estimate. jsPDF is
// imported dynamically so it only loads when the user actually clicks download.
export async function downloadEstimatePdf(report: EstimateReport): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })

  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const M = 56
  const contentW = pageW - M * 2
  const ink: [number, number, number] = [17, 24, 39]
  const soft: [number, number, number] = [75, 85, 99]
  const faint: [number, number, number] = [156, 163, 175]
  let y = M

  // Brand header
  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(...ink)
  doc.text('Ballpark', M, y)
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(...faint)
  doc.text(SITE, pageW - M, y, { align: 'right' })
  y += 16
  doc.setDrawColor(229, 231, 235).line(M, y, pageW - M, y)
  y += 28

  // Tool title + generated date
  doc.setFont('helvetica', 'bold').setFontSize(14).setTextColor(...ink)
  doc.text(report.toolTitle, M, y)
  y += 16
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(...faint)
  doc.text(`Estimate generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, M, y)
  y += 30

  // Estimated range
  doc.setFontSize(9).setTextColor(...faint)
  doc.text('ESTIMATED SETTLEMENT RANGE', M, y)
  y += 24
  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(...ink)
  doc.text(`${formatUSD(report.result.low)} to ${formatUSD(report.result.high)}`, M, y)
  y += 24
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(...soft)
  doc.text(`Economic damages: ${formatUSD(report.result.economic)}      Pain & suffering: ${formatUSD(report.result.painSuffering)}`, M, y)
  y += 30

  // Inputs
  doc.setDrawColor(229, 231, 235).line(M, y - 14, pageW - M, y - 14)
  doc.setFont('helvetica', 'bold').setFontSize(11).setTextColor(...ink)
  doc.text('Your inputs', M, y)
  y += 20
  doc.setFont('helvetica', 'normal').setFontSize(10)
  for (const f of report.fields) {
    doc.setTextColor(...faint).text(f.label, M, y)
    doc.setTextColor(...ink).text(f.value, M + 230, y)
    y += 16
  }
  y += 12

  // State note
  if (report.stateNote) {
    doc.setFontSize(10).setTextColor(...soft)
    const lines = doc.splitTextToSize(report.stateNote, contentW)
    doc.text(lines, M, y)
  }

  // Disclaimer pinned to the bottom
  doc.setDrawColor(229, 231, 235).line(M, pageH - 150, pageW - M, pageH - 150)
  doc.setFont('helvetica', 'bold').setFontSize(9).setTextColor(...soft)
  doc.text('Important', M, pageH - 132)
  doc.setFont('helvetica', 'normal').setTextColor(...faint)
  doc.text(doc.splitTextToSize(DISCLAIMER, contentW), M, pageH - 118)

  doc.save('ballpark-settlement-estimate.pdf')
}
